# -*- coding: utf-8 -*-
"""Bản dịch mô tả module sang tiếng Việt cho Web UI."""

# Tên module (get_name()) -> mô tả tiếng Việt
MODULE_DOCS_VI = {
    'get_info': 'Lấy thông tin về một hoặc nhiều máy trạm',
    'shell_exec': 'Chạy lệnh shell trên máy trạm',
    'edit': 'Chỉnh sửa file từ xa (tải → sửa → tải lên)',
    'download': 'Tải file hoặc thư mục từ máy trạm',
    'upload': 'Tải file hoặc thư mục lên máy trạm',
    'ps': 'Liệt kê tiến trình',
    'ls': 'Liệt kê file trong hệ thống',
    'cat': 'Xem nội dung file',
    'cd': 'Đổi thư mục làm việc',
    'pwd': 'Xem thư mục làm việc hiện tại',
    'rm': 'Xóa file hoặc thư mục',
    'cp': 'Sao chép file hoặc thư mục',
    'mv': 'Di chuyển file hoặc thư mục',
    'mkdir': 'Tạo thư mục rỗng',
    'date': 'Lấy ngày giờ hiện tại',
    'getuid': 'Lấy tên người dùng',
    'getpid': 'Lấy thông tin tiến trình',
    'getppid': 'Lấy thông tin tiến trình cha',
    'exit': 'Thoát phiên trên máy trạm',
    'ip': 'Liệt kê giao diện mạng',
    'dns': 'Tra tên miền từ IP và ngược lại',
    'alive': 'Gửi gói keepalive ở mức rpyc',
    'check_vm': 'Kiểm tra có đang chạy trên máy ảo không',
    'getdomain': 'Lấy bộ điều khiển miền chính',
    'display': 'Đặt biến môi trường display',
    'gpstracker': 'Tương tác với GPS',
    'contacts': 'Lấy danh bạ',
    'call': 'Lấy chi tiết cuộc gọi',
    'get_hwuuid': 'Lấy UUID (DMI) hoặc machine-id (dbus/linux)',
    'drives': 'Liệt kê ổ đĩa hợp lệ trong hệ thống',
    'clear_logs': 'Xóa nhật ký sự kiện',
    'become': 'Chuyển sang người dùng khác',
    'interactive_shell': 'Mở shell tương tác trên máy trạm',
    'hide_process': 'Sửa argv & env của tiến trình hiện tại để ít bị chú ý',
    'lock_screen': 'Khóa phiên màn hình',
    'process_kill': 'Kết thúc tiến trình',
    'msgbox': 'Hiện hộp thoại thông báo',
    'last': 'Liệt kê phiên terminal',
    'persistence': 'Bật / tắt tự chạy khi khởi động',
    'netstat': 'Liệt kê phiên terminal / kết nối mạng',
    'port_scan': 'Quét cổng TCP',
    'outlook': 'Tương tác với phiên Outlook của người dùng đích',
    'zip': 'Nén / giải nén file hoặc thư mục',
    'w': 'Liệt kê phiên terminal',
    'record_mic': 'Ghi âm bằng microphone',
    'text_to_speach': 'Dùng chức năng đọc chữ thành tiếng (Android)',
    'shellcode_exec': 'Chạy shellcode đã cung cấp trên máy trạm',
    'vibrate': 'Kích hoạt rung (điện thoại/tablet)',
    'shares': 'Liệt kê thư mục chia sẻ và quyền (local/remote)',
    'rdp': 'Bật/tắt RDP hoặc kiểm tra thông tin đăng nhập',
    'webcamsnap': 'Chụp ảnh webcam',
    'services': 'Liệt kê dịch vụ',
    'users': 'Lấy danh sách người dùng đang đăng nhập',
    'sudo_alias': 'Ghi alias cho sudo để lấy mật khẩu',
    'ssh': 'Máy khách SSH',
    'rdesktop': 'Bắt đầu phiên remote desktop qua trình duyệt websocket',
    'psexec': 'Chạy lệnh từ xa qua smbexec hoặc wmiexec',
    'pyexec': 'Chạy mã Python trên máy trạm',
    'screenshot': 'Chụp màn hình',
    'search': 'Duyệt thư mục và tìm chuỗi trong file',
    'socks5proxy': 'Chạy proxy socks5 qua máy trạm',
    'portfwd': 'Chuyển tiếp cổng local/remote (openssh -L/-R)',
    'cloudinfo': 'Lấy metadata EC2/DigitalOcean',
    'tcpdump': 'Một số chức năng giống tcpdump',
    'creddump': 'Tải hive từ Windows từ xa và dump thông tin đăng nhập',
    'scapy_shell': 'Mở shell Python tương tác trên máy trạm',
    'pyshell': 'Mở shell Python tương tác trên máy trạm',
    'smbspider': 'Duyệt thư mục SMB và tìm chuỗi trong file',
    'pywerview': 'Viết lại một số chức năng PowerView bằng Python',
    'pexec': 'Chạy lệnh shell không tương tác trên máy trạm (nền, popen)',
    'apps': 'Quản lý ứng dụng',
    'impersonate': 'Liệt kê / mạo danh token tiến trình',
    'beroot': 'Tìm đường leo thang đặc quyền',
    'getsystem': 'Nâng đặc quyền (getsystem)',
    'privesc_checker': 'Script leo thang đặc quyền Linux',
    'linux_stealth': 'Ẩn tiến trình khỏi netstat, ss, ps, lsof bằng binary chỉnh sửa',
    'keylogger': 'Ghi lại phím gõ',
    'nbnsspoof': 'Bắt NBNS và giả mạo phản hồi NBNS',
    'netcreds': 'Thu thập thông tin đăng nhập từ mạng',
    'netmon': 'Giám sát lưu lượng mạng',
    'credcap': 'Thu thập thông tin đăng nhập',
    'load_package': 'Tải gói Python',
    'duplicate': 'Nhân bản phiên',
    'inveigh': 'Công cụ LLMNR/NBNS spoofing',
    'mimishell': 'Shell Mimikatz',
    'memstrings': 'Tìm chuỗi trong bộ nhớ',
    'mimipy': 'Mimikatz Python',
    'powerview': 'PowerView',
    'memory_exec': 'Thực thi trong bộ nhớ',
    'igd': 'Máy khách UPnP IGD',
    'bypassuac': 'Bypass UAC',
    'forward': 'Chuyển tiếp cổng',
    'http': 'Máy chủ HTTP',
    'migrate': 'Di chuyển sang tiến trình khác',
    'mapped': 'Liệt kê ổ đĩa ánh xạ',
    'logs': 'Xem / quản lý nhật ký',
    'loot_memory': 'Lấy dữ liệu từ bộ nhớ',
    'isearch': 'Tìm file theo index',
    'hashmon': 'Giám sát bảng băm',
    'mouselogger': 'Ghi lại thao tác chuột',
    'msgbox': 'Hiện hộp thoại',
    'odbc': 'Truy vấn ODBC',
    'pipecatcher': 'Bắt lệnh qua pipe',
    'process_kill': 'Kết thúc tiến trình',
    'rwmic': 'WMI từ xa',
    'stat': 'Thông tin file',
    'tasks': 'Liệt kê / quản lý tác vụ',
    'ttyrec': 'Ghi lại phiên terminal',
    'write': 'Ghi nội dung vào file',
    'x509': 'Thao tác chứng chỉ X.509',
    'usniper': 'Thu thập thông tin đăng nhập',
    'wmic': 'WMI',
}
